### ISSUE TITLE
Monokai Theme Bug

### ISSUE THREAD

**Issue by farfalk** [avasconcelos114/mattermost-themes#44] opened 2020-04-17 10:20 UTC
If you copy and paste the current monokai theme code, my application becomes completely white and unresponsive. I realized `"dndIndicator"` and `"errorTextColor"` were missing. My Mattermost version is 5.21.
This is instead a functioning proposal:
```json
{
  "awayIndicator": "#B8B884",
  "buttonBg": "#90AD58",
  "buttonColor": "#FFFFFF",
  "centerChannelBg": "#FFFFFF",
  "centerChannelColor": "#444444",
  "codeTheme": "monokai",
  "dndIndicator": "#f74343",
  "errorTextColor": "#fd5960",
  "linkColor": "#90AD58",
  "mentionBg": "#7E9949",
  "mentionColor": "#FFFFFF",
  "mentionHighlightBg": "#54850C",
  "mentionHighlightLink": "#FFFFFF",
  "newMessageSeparator": "#90AD58",
  "onlineIndicator": "#99CB3F",
  "sidebarBg": "#262626",
  "sidebarHeaderBg": "#363636",
  "sidebarHeaderTextColor": "#FFFFFF",
  "sidebarText": "#FFFFFF",
  "sidebarTextActiveBorder": "#7E9949",
  "sidebarTextActiveColor": "#FFFFFF",
  "sidebarTextHoverBg": "#525252",
  "sidebarUnreadText": "#CCCCCC"
}
```
I'm opening an issue and not a pull request because I feel this might be version dependent.

**Comment by avasconcelos114** [comment] 2020-04-17 12:05
Oh awesome! Thank you for finding this out, I just tested on my server and the issue totally reproduces

It looks as though the original docs that had this theme has since been outdated and the app runs into trouble when trying to read values that aren't there.

I'll be sure to patch it with your proposed changes :)

**Comment by avasconcelos114** [comment] 2020-04-17 12:19
The issue should be fixed now :)

Thanks again for reporting it!

**Closed by avasconcelos114** 2020-04-17 12:19 UTC
